### ISSUE TITLE
Egg requests

### ISSUE THREAD

**Issue by NoodlesDev987** [lazybytez/custom-eggs#15]
I think that this eggs should be created:
- MongoDB egg
- noSQLclient egg (https://www.nosqlclient.com it was before hostable on heroku, but now it is not because they removed mlab extension)
- RedisDB egg

**Comment by pascal-zarrad** [comment]
A MongoD and Redis egg are available and maintained by parkervcp and an active community.

You can find them here:
**MongoDB:** https://github.com/parkervcp/eggs/tree/master/database/nosql/mongodb
**Redis:** https://github.com/parkervcp/eggs/tree/master/database/redis

The noSQLclient egg would be a good idea. But right now, no one of the team uses MongoDB. When the time arrives where we use MongoDB, we might implement one. 
But feel free to contribute one if you'd like to. As this might also be a great start for someone interrested in making eggs, I will mark it as good first issue.

**Comment by NoodlesDev987** [comment]
Ok, I use MongoDB and need some web-based GUI. Before it was hostable on heroku, but now it is not :/

**Comment by pascal-zarrad** [comment]
Until today, we still won't add this egg bby ourself. I will close this issue for now.
