### ISSUE TITLE
Egg won't stop installing

### ISSUE THREAD

**Issue by SlayorPlayz** [lazybytez/custom-eggs#27]
The egg wont stop installing.

**Comment by SlayorPlayz** [comment]
although it works when I set the version to 2.4.3

**Comment by pascal-zarrad** [comment]
@SlayorPlayz we have currently three maintained eggs in this repository. Which one of them won't stop installing?

**Comment by pascal-zarrad** [comment]
I checked the Caddy egg as I think it is the only one that might be the one you mean. I didn't had any issues during installation with using "latest" as the version to install.

Can you maybe tell me the steps you did when installing/reinstalling and also check your Wings log for some errors?

**Comment by pascal-zarrad** [comment]
As there was no answer for a long time and the installation process has been reworked a bit anyways, I will close the ticket for now.
