### ISSUE TITLE
Cassandra egg

### ISSUE THREAD

**Issue by BasToTheMax** [lazybytez/custom-eggs#30]
Hello!

Can U add an Cassandra egg? Cassandra is a database.

I need it for my (big) project :)

Thx for adding it :)

**Comment by pascal-zarrad** [comment]
Hello,

I saw that you already requested the egg in the official [parkervcp/eggs](https://github.com/parkervcp/eggs) repository.
That issue caught my attention and I might add it there in the next days. I think the normal Cassandra egg fits better in the official repo, as this repo is just for stuff that we don't think fits in the official repo.

**Comment by BasToTheMax** [comment]
Okay.

No problem.

Thx for your response :)
