### ISSUE TITLE
caddy egg question

### ISSUE THREAD

**Issue by nickdevnl** [lazybytez/custom-eggs#36]
**Is your question related to a feature? If so, please describe:**  
A clear and concise description of what the question is about. Ex. I don't know how [...]
so i got a error with the caddy egg and it won't start on the port of the servers

**Additional context:**  
2021/08/22 10:01:04.902 WARN    input is not formatted with 'caddy fmt' {"adapter": "caddyfile", "file": "/home/container/Caddyfile", "line": 2}

**Comment by pascal-zarrad** [comment]
Hello, I will investigate this issue and provide a fix as far as possible.

As we use the file parser to automatically set the port, we might have a problem here.
It is possible that a fix of this issue won't be easily done.

**Comment by pascal-zarrad** [comment]
The linked pull request updates the Caddy egg with a new structure.
With this new version, I wasn't able to reproduce the malformed Caddyfile.

Note that if you do manual changes to the Caddyfile, you must ensure that it is formatted properly. If it's not, you can download the file and run `caddy fmt` (optionally you can also just abuse the Pterodactyl startup command to do so).

If the issue still persists or you encounter additional issues, please open a new ticket.
