### ISSUE TITLE
[feature] add ionCube to docker image

### ISSUE THREAD

**Issue by anondev-sudo** [lazybytez/custom-eggs#47]
![image](https://user-images.githubusercontent.com/85408287/167618059-2ccfc99e-2c28-4357-86c1-c22b28e1d609.png)

How to install it there?

**Comment by anondev-sudo** [comment]
After unzipping their loader-wizard and visiting the url with the script the server crashes 
![image](https://user-images.githubusercontent.com/85408287/167618544-a5eb6f34-9284-48e3-9073-4c423ddfbea2.png)

**Comment by pascal-zarrad** [comment]
This isn't a bug, its a missing feature.

It is not installed on the Container. You need to run the wizard from command line and not from the webserver.
But as you're not root, you wont be able to install it as recommended. I don't recommend a hacky solution.

As it is a PHP extension, it has to be added to the container image(s).
Feel free to add and PR it if you'd like to.

If not, I will see if I can find time to add it in the near future.

**Comment by pascal-zarrad** [comment]
Hi,

I'm sorry to tell you that we decided to not add the ionCube loader in our Docker images, as the ionCube loader is proprietary software.

Feel free to fork the repository and add the ionCube loader to the PHP image(s) in your fork.
